version: 2.0

jobs:
  build:
    working_directory: ~/mns
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          key: mns-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: mns-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      #  - run: xvfb-run -a npm run test TODO@Idrice
      #  - run: xvfb-run -a npm run e2e
      - run:
          name: Change the current directory to backend
          command: echo "A Command in CircleCI "
      - run:
          name: Just to test current directory
          command: dir
