version: 2.0

jobs:
  build:
   # working_directory: ~/MNS/backend
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout # check out source code to working directory
      - run :
         name: Just to test current directory
         command: ls ~/MNS/backend
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: MNS-{{ checksum "pom.xml" }} 
      - run: 
         name: Gets the project dependencies  
         command: mvn dependency:go-offline  
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: MNS-{{ checksum "pom.xml" }}         
      - run:
         name: Change the current directory to backend
         command : echo "A Command in CircleCI "
      - run :
         name: Just to test current directory
         command: dir
      - run: 
         name: CLEAN   
         command : mvn clean  
      - run: 
         name: PACKAGIN (Run all test) 
         command : mvn   package